"""Parser Registry - Synced from siem-tool"""
# All parsers from siem-tool
ALL_PARSERS = [
    # Web Server (18 types)
    {'name': 'Apache', 'logType': 'apache', 'category': 'webserver'},
    {'name': 'Apache Error', 'logType': 'apache_error', 'category': 'webserver'},
    {'name': 'NGINX', 'logType': 'nginx', 'category': 'webserver'},
    {'name': 'NGINX Error', 'logType': 'nginx_error', 'category': 'webserver'},
    {'name': 'IIS', 'logType': 'iis', 'category': 'webserver'},
    {'name': 'Django', 'logType': 'django', 'category': 'webserver'},
    {'name': 'Flask', 'logType': 'flask', 'category': 'webserver'},
    {'name': 'Laravel', 'logType': 'laravel', 'category': 'webserver'},
    {'name': 'Rails', 'logType': 'rails', 'category': 'webserver'},
    {'name': 'Express.js', 'logType': 'express', 'category': 'webserver'},
    {'name': 'FastAPI', 'logType': 'fastapi', 'category': 'webserver'},
    {'name': 'Gunicorn', 'logType': 'gunicorn', 'category': 'webserver'},
    {'name': 'Uvicorn', 'logType': 'uvicorn', 'category': 'webserver'},
    {'name': 'PHP-FPM', 'logType': 'php_fpm', 'category': 'webserver'},
    {'name': 'Caddy', 'logType': 'caddy', 'category': 'webserver'},
    {'name': 'HAProxy', 'logType': 'haproxy', 'category': 'webserver'},
    {'name': 'Spring Boot', 'logType': 'spring_boot', 'category': 'webserver'},
    {'name': 'ASP.NET Core', 'logType': 'aspnet_core', 'category': 'webserver'},
    # Database (14 types)
    {'name': 'MySQL Error', 'logType': 'mysql_error', 'category': 'database'},
    {'name': 'MySQL Query', 'logType': 'mysql_query', 'category': 'database'},
    {'name': 'MySQL Slow', 'logType': 'mysql_slow', 'category': 'database'},
    {'name': 'PostgreSQL Error', 'logType': 'postgres_error', 'category': 'database'},
    {'name': 'PostgreSQL Auth', 'logType': 'postgres_auth', 'category': 'database'},
    {'name': 'PostgreSQL Stmt', 'logType': 'postgres_statement', 'category': 'database'},
    {'name': 'Oracle Alert', 'logType': 'oracle_alert', 'category': 'database'},
    {'name': 'Oracle Listener', 'logType': 'oracle_listener', 'category': 'database'},
    {'name': 'Oracle Audit', 'logType': 'oracle_audit', 'category': 'database'},
    {'name': 'SQL Server Error', 'logType': 'sqlserver_error', 'category': 'database'},
    {'name': 'SQL Server Audit', 'logType': 'sqlserver_audit', 'category': 'database'},
    {'name': 'SQL Server Tx', 'logType': 'sqlserver_transaction', 'category': 'database'},
    {'name': 'MongoDB', 'logType': 'mongodb_server', 'category': 'database'},
    {'name': 'MongoDB Audit', 'logType': 'mongodb_audit', 'category': 'database'},
    # Firewall (12 types)
    {'name': 'Windows FW', 'logType': 'windows_firewall', 'category': 'firewall'},
    {'name': 'iptables', 'logType': 'iptables', 'category': 'firewall'},
    {'name': 'UFW', 'logType': 'ufw', 'category': 'firewall'},
    {'name': 'nftables', 'logType': 'nftables', 'category': 'firewall'},
    {'name': 'firewalld', 'logType': 'firewalld', 'category': 'firewall'},
    {'name': 'Palo Alto', 'logType': 'palo_alto', 'category': 'firewall'},
    {'name': 'FortiGate', 'logType': 'fortigate', 'category': 'firewall'},
    {'name': 'Cisco ASA', 'logType': 'cisco_asa', 'category': 'firewall'},
    {'name': 'Check Point', 'logType': 'checkpoint', 'category': 'firewall'},
    {'name': 'AWS VPC', 'logType': 'aws_vpc_flow', 'category': 'firewall'},
    {'name': 'Azure NSG', 'logType': 'azure_nsg', 'category': 'firewall'},
    {'name': 'GCP VPC', 'logType': 'gcp_vpc', 'category': 'firewall'},
    # Mail (9 types)
    {'name': 'Postfix', 'logType': 'postfix', 'category': 'mail'},
    {'name': 'Sendmail', 'logType': 'sendmail', 'category': 'mail'},
    {'name': 'Exim', 'logType': 'exim', 'category': 'mail'},
    {'name': 'Dovecot', 'logType': 'dovecot', 'category': 'mail'},
    {'name': 'Courier', 'logType': 'courier', 'category': 'mail'},
    {'name': 'Exchange', 'logType': 'exchange', 'category': 'mail'},
    {'name': 'Amavis', 'logType': 'amavis', 'category': 'mail'},
    {'name': 'SpamAssassin', 'logType': 'spamassassin', 'category': 'mail'},
    {'name': 'MailScanner', 'logType': 'mailscanner', 'category': 'mail'},
    # Auth (2 types)
    {'name': 'SSH Auth', 'logType': 'ssh_auth', 'category': 'auth'},
    {'name': 'PAM', 'logType': 'pam', 'category': 'auth'},
    # System (5 types)
    {'name': 'Syslog', 'logType': 'syslog', 'category': 'system'},
    {'name': 'Systemd', 'logType': 'systemd', 'category': 'system'},
    {'name': 'Kernel', 'logType': 'kernel', 'category': 'system'},
    {'name': 'Audit', 'logType': 'audit', 'category': 'system'},
    {'name': 'Windows Sys', 'logType': 'windows_system', 'category': 'system'},
    # Network (5 types)
    {'name': 'FileZilla', 'logType': 'filezilla', 'category': 'network'},
    {'name': 'vsftpd', 'logType': 'vsftpd', 'category': 'network'},
    {'name': 'ProFTPD', 'logType': 'proftpd', 'category': 'network'},
    {'name': 'xferlog', 'logType': 'xferlog', 'category': 'network'},
    {'name': 'IIS FTP', 'logType': 'iis_ftp', 'category': 'network'},
    # Cloud (5 types)
    {'name': 'Cloudflare', 'logType': 'cloudflare', 'category': 'cloud'},
    {'name': 'AWS CloudTrail', 'logType': 'aws_cloudtrail', 'category': 'cloud'},
    {'name': 'AWS GuardDuty', 'logType': 'aws_guardduty', 'category': 'cloud'},
    {'name': 'Azure', 'logType': 'azure_activity', 'category': 'cloud'},
    {'name': 'GCP Audit', 'logType': 'gcp_audit', 'category': 'cloud'},
    # Container (2 types)
    {'name': 'Kubernetes', 'logType': 'kubernetes', 'category': 'container'},
    {'name': 'Docker', 'logType': 'docker', 'category': 'container'},
    # Application (7 types)
    {'name': 'Elasticsearch', 'logType': 'elasticsearch', 'category': 'application'},
    {'name': 'Redis', 'logType': 'redis', 'category': 'application'},
    {'name': 'RabbitMQ', 'logType': 'rabbitmq', 'category': 'application'},
    {'name': 'Kafka', 'logType': 'kafka', 'category': 'application'},
    {'name': 'Zookeeper', 'logType': 'zookeeper', 'category': 'application'},
    {'name': 'Moodle', 'logType': 'moodle_lms', 'category': 'application'},
    {'name': 'Squid', 'logType': 'squid', 'category': 'application'},
    # Security (5 types)
    {'name': 'Suricata', 'logType': 'suricata', 'category': 'security'},
    {'name': 'Zeek', 'logType': 'zeek', 'category': 'security'},
    {'name': 'Ossec', 'logType': 'ossec', 'category': 'security'},
    {'name': 'Fail2ban', 'logType': 'fail2ban', 'category': 'security'},
    {'name': 'Auth0', 'logType': 'auth0', 'category': 'security'},
    # Generic
    {'name': 'Unknown', 'logType': 'unknown', 'category': 'generic'},
]
